enum CryptoCurrencies {
    AAVE  = 'Aave',
    ADA   = 'Cardano',
    ALGO  = 'Algorland',
    ATOM  = 'Cosmos',
    AVAX  = 'Avalanche',
    BAT   = 'Basic Attention Token',
    BCH   = 'Bitcoin Cash',
    BNB   = 'Binance Coin',
    BTC   = 'Bitcoin',
    BUSD  = 'Binance USD',
    COMP  = 'Compound',
    DASH  = 'Dash',
    DAI   = 'Dai',
    DOT   = 'Polkadot',
    DNT   = 'District0x',
    EOS   = 'EOS',
    ETC   = 'Ethereum Classic',
    ETH   = 'Ethereum',
    FIL   = 'Filecoin',
    GLM   = 'Golem',
    GRT   = 'The Graph',
    LINK  = 'Chainlink',
    LTC   = 'Litecoin',
    MKR   = 'Maker',
    NEO   = 'Neo',
    ONT   = 'Ontology',
    REN   = 'Ren',
    REP   = 'Augur',
    STORJ = 'Storj',
    USDC  = 'USD Coin',
    USDT  = 'Tether',
    VET   = 'VeChain',
    XLM   = 'Stellar',
    XMR   = 'Monero',
    XTZ   = 'Tezos',
    XRP   = 'Ripple',
    YFI   = 'yearn.finance',
    ZEC   = 'Zcash',
    ZRX   = '0x'
}

export default CryptoCurrencies;
